### ISSUE TITLE
Changes to Prologue

### ISSUE THREAD

**Issue by JamieBallingall** [and-pete/purescript-halogen-template-extended#4]
A couple of things we might, or might not, want to do to Prologue. Especially to help out newer users.

1. Make all imports explicit and add a comment as to why that is best practice
2. Comment as to why Prologue exports itself
3. Import only those modules that are used in the project with a comment that a typical Prologue would also contain the missing ones. We could remove `Data.Bifunctor`, `Data.Foldable`, `Data.Newtype` and `Data.Void`. This would also remove the need for explaining why `Data.Newtype` doesn't import everything
4. Change `import Prelude hiding ((/))` to just `import Prelude` and then change `import Prologue` to `import Prologue hiding ((/))` in `App.Data.Route`. That puts the `hiding` closer to where it actually matters.

Thoughts?

**Comment by and-pete** [comment]
Thanks for the suggestions! I essentially agree on all counts. Your questions on the Discord have been teaching me things I either never learned in the first place or forgot (e.g. the ability to have a single module with open imports whose name doesn't matter).

1. Yes, 100% right. I should have followed the structure of the [actual Prelude structure](https://github.com/purescript/purescript-prelude/blob/a0aa536aae9820aeb3d8ca04a559753c7390a9d0/src/Prelude.purs) here
2. I copied the `Prologue` from another project where I had a few other combinators/helpers defined in the module itself, hence the self re-export. I have no particular opinion on whether the individual functions should be exported in that case or the entire `Prologue` module re-exported, but it's probably simplest in this case to delete the module's self re-export.
3. I don't know how `Data.Void` slipped in there as it's already exported by regular `Prelude`.

Hmm 🤔 I guess a meta question here that's worth considering at this point is whether this custom prelude should even be within scope of this template, that was meant to just focus on routing and the global store 😅

And, if it is worth keeping the custom prelude in, whether the purpose of including it would be to:
*  explicitly import and then re-export ALL of the classes / types / functions from a select set of extra modules (on top of those exported by the regular `Prelude`).
    *  The intent being that a user working on a cloned version of this template would _not_ need to modify the explicit imports of any of the existing modules in the `Prologue` module as they use new functions/etc. from any of those modules. That, for the most part, it would be a case of "set it and forget it" like the regular `Prelude`, but just giving you more things in scope by default.
    *  e.g. I haven't used `traverse`/`traverse_`/`for_`/`maybe`/`either`/`bimap`/etc. in the template, but I can near guarantee that as a project grows not much larger than this template that I would use them. And what I'd want from a custom `Prelude` is for those to already be in scope.
*  explicitly import and re-export from `Prologue` only those functions explicitly used by this template
    *  This would require the user to manage those explicit import in the `Prologue` module as they want to use more features from each of its re-exported modules.
    *  Once you're managing the explicit imports in `Prologue` as your project grows, I feel as though — instead of using a custom prelude at all — I'd likely just use the editor/IDE's feature of automating the management of your import list in each project module directly whenever you use a function that's not currently in scope. It's much faster.

Back to 3., after writing the above I'm now leaning toward keeping in the packages & modules (like `bifunctors` and `foldable-traversable`) that aren't used by this project. And adding a note to the top of the import list in the `Prologue` module that states that not all of the modules being imported are being used by this this template, but that I would expect to use them before much longer as a project grows larger.

It doesn't however include any particularly opinionated library choices like between `affjax` / `web-fetch` / `milkis` or between `argonaut` / `codec-argonaut` / `simple-json`, etc.

4. Good call on moving the hiding of `(/)` to the one module where it matters!

I'll make a PR to the above effect. :) Thanks again for the good ideas.
